const types = {
  RESET_WORKOUT_PROGRESS: 'WORKOUTS/RESET_WORKOUT_PROGRESS',

  SAVE_WORKOUT_REQUEST: 'WORKOUTS/SAVE_WORKOUT_REQUEST',
  SAVE_WORKOUT_SUCCESS: 'WORKOUTS/SAVE_WORKOUT_SUCCESS',
  SAVE_WORKOUT_FAILURE: 'WORKOUTS/SAVE_WORKOUT_FAILURE',

  EDIT_WORKOUT_REQUEST: 'WORKOUTS/EDIT_WORKOUT_REQUEST',
  EDIT_WORKOUT_SUCCESS: 'WORKOUTS/EDIT_WORKOUT_SUCCESS',
  EDIT_WORKOUT_FAILURE: 'WORKOUTS/EDIT_WORKOUT_FAILURE',

  GET_WORKOUT_LOGS_REQUEST: 'WORKOUTS/GET_WORKOUT_LOGS_REQUEST',
  GET_WORKOUT_LOGS_SUCCESS: 'WORKOUTS/GET_WORKOUT_LOGS_SUCCESS',
  GET_WORKOUT_LOGS_FAILURE: 'WORKOUTS/GET_WORKOUT_LOGS_FAILURE',
};

export default types;
