const types = {
  SAVE_WORKOUT_REQUEST: 'WORKOUTS/SAVE_WORKOUT_REQUEST',
  SAVE_WORKOUT_SUCCESS: 'WORKOUTS/SAVE_WORKOUT_SUCCESS',
  SAVE_WORKOUT_FAILURE: 'WORKOUTS/SAVE_WORKOUT_FAILURE',
};

export default types;
