const types = {
  GET_PRESETS_REQUEST: 'EXERCISES/GET_PRESETS_REQUEST',
  GET_PRESETS_SUCCESS: 'EXERCISES/GET_PRESETS_SUCCESS',
  GET_PRESETS_FAILURE: 'EXERCISES/GET_PRESETS_FAILURE',
};

export default types;
