const types = {
  GET_PRESETS_REQUEST: 'EXERCISES/GET_PRESETS_REQUEST',
  GET_PRESETS_SUCCESS: 'EXERCISES/GET_PRESETS_SUCCESS',
  GET_PRESETS_FAILURE: 'EXERCISES/GET_PRESETS_FAILURE',

  GET_NAMES_REQUEST: 'EXERCISES/GET_NAMES_REQUEST',
  GET_NAMES_SUCCESS: 'EXERCISES/GET_NAMES_SUCCESS',
  GET_NAMES_FAILURE: 'EXERCISES/GET_NAMES_FAILURE',
};

export default types;
