const types = {
  LOGIN_REQUEST: 'AUTH/LOGIN_REQUEST',
  LOGIN_SUCCESS: 'AUTH/LOGIN_SUCCESS',
  LOGIN_FAILURE: 'AUTH/LOGIN_FAILURE',

  GET_USER_DATA_REQUEST: 'AUTH/GET_USER_DATA_REQUEST',
  GET_USER_DATA_SUCCESS: 'AUTH/GET_USER_DATA_SUCCESS',
  GET_USER_DATA_FAILURE: 'AUTH/GET_USER_DATA_FAILURE',

  LOGOUT: 'AUTH/LOGOUT',

  UPDATE_PREFERENCES_REQUEST: 'AUTH/UPDATE_PREFERENCES_REQUEST',
  UPDATE_PREFERENCES_SUCCESS: 'AUTH/UPDATE_PREFERENCES_SUCCESS',
  UPDATE_PREFERENCES_FAILURE: 'AUTH/UPDATE_PREFERENCES_FAILURE',

  DELETE_USER_REQUEST: 'AUTH/DELETE_USER_REQUEST',
  DELETE_USER_SUCCESS: 'AUTH/DELETE_USER_SUCCESS',
  DELETE_USER_FAILURE: 'AUTH/DELETE_USER_FAILURE',
};

export default types;
