const types = {
  LOGIN_REQUEST: 'AUTH/LOGIN_REQUEST',
  LOGIN_SUCCESS: 'AUTH/LOGIN_SUCCESS',
  LOGIN_FAILURE: 'AUTH/LOGIN_FAILURE',

  GET_USER_DATA_REQUEST: 'AUTH/GET_USER_DATA_REQUEST',
  GET_USER_DATA_SUCCESS: 'AUTH/GET_USER_DATA_SUCCESS',
  GET_USER_DATA_FAILURE: 'AUTH/GET_USER_DATA_FAILURE',

  LOGOUT: 'AUTH/LOGOUT',

  SET_DISPLAYED_WEIGHT_UNIT: 'AUTH/SET_DISPLAYED_WEIGHT_UNIT',
};

export default types;
