const types = {
  LOGIN_REQUEST: 'AUTH/LOGIN_REQUEST',
  LOGIN_SUCCESS: 'AUTH/LOGIN_SUCCESS',
  LOGIN_FAILURE: 'AUTH/LOGIN_FAILURE',
  LOGOUT: 'AUTH/LOGOUT',

  SET_DISPLAYED_WEIGHT_UNIT: 'AUTH/SET_DISPLAYED_WEIGHT_UNIT',
};

export default types;
