const types = {
  GET_PRESETS_REQUEST: 'ROUTINES/GET_PRESETS_REQUEST',
  GET_PRESETS_SUCCESS: 'ROUTINES/GET_PRESETS_SUCCESS',
  GET_PRESETS_FAILURE: 'ROUTINES/GET_PRESETS_FAILURE',
};

export default types;
