const types = {
  GET_PRESET_ROUTINES_REQUEST: 'ROUTINES/GET_PRESET_ROUTINES_REQUEST',
  GET_PRESET_ROUTINES_SUCCESS: 'ROUTINES/GET_PRESET_ROUTINES_SUCCESS',
  GET_PRESET_ROUTINES_FAILURE: 'ROUTINES/GET_PRESET_ROUTINES_FAILURE',

  GET_CUSTOM_ROUTINES_REQUEST: 'ROUTINES/GET_CUSTOM_ROUTINES_REQUEST',
  GET_CUSTOM_ROUTINES_SUCCESS: 'ROUTINES/GET_CUSTOM_ROUTINES_SUCCESS',
  GET_CUSTOM_ROUTINES_FAILURE: 'ROUTINES/GET_CUSTOM_ROUTINES_FAILURE',

  SAVE_ROUTINE_REQUEST: 'ROUTINES/SAVE_ROUTINE_REQUEST',
  SAVE_ROUTINE_SUCCESS: 'ROUTINES/SAVE_ROUTINE_SUCCESS',
  SAVE_ROUTINE_FAILURE: 'ROUTINES/SAVE_ROUTINE_FAILURE',
};

export default types;
