const types = {
  GET_PRESETS_REQUEST: 'ROUTINES/GET_PRESETS_REQUEST',
  GET_PRESETS_SUCCESS: 'ROUTINES/GET_PRESETS_SUCCESS',
  GET_PRESETS_FAILURE: 'ROUTINES/GET_PRESETS_FAILURE',

  SAVE_ROUTINE_REQUEST: 'ROUTINES/SAVE_ROUTINE_REQUEST',
  SAVE_ROUTINE_SUCCESS: 'ROUTINES/SAVE_ROUTINE_SUCCESS',
  SAVE_ROUTINE_FAILURE: 'ROUTINES/SAVE_ROUTINE_FAILURE',
};

export default types;
